language: python

python:
     - 3.6.8

install:
    - pip install -r requirements.txt

script:
    - python manage.py test
    - python manage.py collectstatic --noinput

#deploy
deploy:
    provider: heroku
    api_key:
        secure: "jdAKxGa1PeBl+NHaAhYyno51kO5sHDiQtkQO67JkedeTQUCjVUjbntCGSdZpQkn2X1Y29MEGNzUS9KIB3MNG65htFw4Lazu8GDCyXkQTdJWv0jnZpKJ/7FJIgqGs87Z7F6FRYHz0tmhNkVNwtWdvmHmmz4BERMysLV5M8+0SEhHr4UVGM6/fSqGf3YVAV1LzEwpbsTMkXdiECEe67J52rrQpuUnZVNHPvPr7St/upneamyx+YVsKAVqzF7OVbCmNR6u8VBo+zYiu4q2Ha9oxSAHaQjSQsMdT44NXlyyHpEkiXDI+re6Kt062CqolqSOrLu7nF/PlnV5iLIcmeFTSezPBy3WRgfmMiA/e9ssJHGQOje9xUxgViq4bsPRIA9yn0tqQ+2AbrPOE1aO+QssDTAplew/Ikxvvt+8LBxTBZJxmc1MOH0M55fX70Ogf+rAtgY7EzPHAWWwHYj1ksET+5YdZ+BzFylLz5dvrWRdHJslGmDO3eLqgWVwi9FSFr+j5TcLFv/7FFV9kxhFV0ftAdSeuDSKsolWNqzzAkhhZvnm2gGVZ51aUA6D1STkXWfEPbCNEoQtpVHgW1uzP3kThSdbs+xjdnsdUOUcu/IMD2sndaS65+t2kM7BU/XTh7kTVPLmR9mWQZzapw7g7uBHqttUBjdAYTOLB20860dhDyJw="

    app: va-vrrt-admin
    on:
        repo: emilyngodby/VRRT-admin-only
