# Generated by Django 3.1.7 on 2021-03-15 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0007_siteid_sitetelephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='ReperationRateEnd',
            field=models.PositiveIntegerField(default=0, help_text='Resperation rate at the end of each session'),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='ReperationRateStart',
            field=models.PositiveIntegerField(default=0, help_text='Resperation rate at the start of each session'),
        ),
    ]
