# Generated by Django 3.1.7 on 2021-03-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0010_auto_20210315_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyinstance',
            old_name='ReperationRateEnd',
            new_name='RespirationRateEnd',
        ),
        migrations.RenameField(
            model_name='surveyinstance',
            old_name='ReperationRateStart',
            new_name='RespirationRateStart',
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='AnxietyEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='AnxietyStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='DelusionsEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='DelusionsStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='DepressionEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='DepressionStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='MobilityEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='MobilityStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='NauseaEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='NauseaStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='RestlessnessEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='RestlessnessStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='TremorsEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='TremorsStart',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='VisiblePainEnd',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='surveyinstance',
            name='VisiblePainStart',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
