# Generated by Django 3.1.7 on 2021-03-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0011_auto_20210315_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='therapyDuration',
            field=models.PositiveIntegerField(default=0, help_text='Length of therapy in minutes'),
        ),
    ]
