# Generated by Django 3.1.7 on 2021-03-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0012_surveyinstance_therapyduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveyinstance',
            old_name='therapyDuration',
            new_name='TherapyDuration',
        ),
    ]
