# Generated by Django 3.1.7 on 2021-03-15 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VRRTController', '0013_auto_20210315_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinstance',
            name='PatientID',
            field=models.CharField(default='VA_00_00', max_length=8),
        ),
    ]
